launcher_name: "kcraft"
launcher_display_name: "KCraft"
launcher_copyright: "KCraft Contributors"
launcher_domain: "github.com/kcraft-org"
launcher_config_file: "kcraft.cfg"
version_major: 1
version_minor: 1
version_channel: "0"
updater_enabled: false
user_agent: "KCraft/1.1"
user_agent_uncached: "KCraft/1.1"
meta_url: "https://raw.githubusercontent.com/kcraft-org/kcraft-meta/master/v1/"
msa_client_id: ""
flame_api_key: ""
imgur_client_id: ""
news_rss_url: "https://github.com/kcraft-org/kcraft/releases.atom"
news_open_url: "https://github.com/kcraft-org/kcraft/releases"
help_url: "https://github.com/kcraft-org/kcraft/issues"
bug_tracker_url: "https://github.com/kcraft-org/kcraft/issues"
translations_url: "https://github.com/kcraft-org/kcraft"
discord_url: "https://github.com/kcraft-org/kcraft/discussions"
subreddit_url: "https://github.com/kcraft-org/kcraft/discussions"
resource_base: "https://resources.download.minecraft.net/"
library_base: "https://libraries.minecraft.net/"
auth_base: "https://authserver.mojang.com/"
imgur_base_url: "https://api.imgur.com/3/"
fmllibs_base_url: "https://maven.minecraftforge.net/"
modpacksch_api_base_url: "https://api.modpacks.ch/"
legacy_ftb_cdn_base_url: "https://dist.creeper.host/FTB2/"
atl_download_server_url: "https://download.nodecdn.net/containers/atl/"
atl_api_base_url: "https://api.atlauncher.com/v1/"
technic_api_base_url: "https://api.technicpack.net/"
technic_api_build: "multimc"
modrinth_staging_url: "https://staging-api.modrinth.com/v2"
modrinth_prod_url: "https://api.modrinth.com/v2"
